# Use root/example as user/password credentials
# docker-compose up -d
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootmongo
    ports:
        - 27017:27017
    volumes:
        - ./docker/mongo:/data/db